---
version: '3.5'
services:
  samba:
    image: xtrasimplicity/samba
    build: .
    environment:
      USERS: # A comma-delimited list of users
    volumes:
      - smbd-conf:/var/lib/samba
    ports:
      - 445:445

volumes:
  smbd-conf: